package com.izv.hibernate;
// Generated 31-ene-2015 12:53:36 by Hibernate Tools 4.3.1



/**
 * Inmueble generated by hbm2java
 */
public class Inmueble  implements java.io.Serializable {


     private Integer id;
     private String direccion;
     private String numero;
     private String precio;
     private String tipo;
     private String descripcion;
     private String imagen;
     private Integer subido;

    public Inmueble() {
    }

    public Inmueble(String direccion, String numero, String precio, String tipo, String descripcion, String imagen, Integer subido) {
       this.direccion = direccion;
       this.numero = numero;
       this.precio = precio;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.imagen = imagen;
       this.subido = subido;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Integer getSubido() {
        return this.subido;
    }
    
    public void setSubido(Integer subido) {
        this.subido = subido;
    }
}


